language: python
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install -r docs-requirements.txt
  - pip install -r test-requirements.txt
  - pip install -r quality-requirements.txt
script:
  - make
after_success:
  - coveralls
