language: python
branches:
    only:
      - master
python:
  - "2.7"
install:
  - pip install coveralls
  - pip install -r docs-requirements.txt
  - pip install -r test-requirements.txt
  - pip install -r quality-requirements.txt
script:
  - make test docs quality
after_success:
  - coveralls