language: python
branches:
    only:
      - master
python:
  - "2.7"
install:
  - pip install tox
  - pip install coveralls
  - pip install sphinx
  - pip install -r doc/requirements.txt
script:
  - make test docs quality
after_success:
  - coveralls